### ISSUE TITLE
After Requiring Error

### ISSUE THREAD

**Issue by sherlock-00** [yeoman/configstore#80]
```
internal/modules/cjs/loader.js:1085
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mnt/e/crypto-command-line/node_modules/configstore/index.js
require() of ES modules is not supported.
require() of /mnt/e/crypto-command-line/node_modules/configstore/index.js from /mnt/e/crypto-command-line/lib/KeyManager.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /mnt/e/crypto-command-line/node_modules/configstore/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/mnt/e/crypto-command-line/lib/KeyManager.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'ERR_REQUIRE_ESM'
```

This is the error I am getting

**Comment by tiagohermano** [comment]
@sherlock-00 did you manage to solve the error?

**Comment by Tushar1998** [comment]
Version 6 
you can't require configstore because the library is now Ecma Script Module(esm) 
use version 5  and you wont get this error

If you still want to use version 6 make your app module by adding property type : "module" in package json

CJS and ESM can't get along 🙃

**Comment by xencodes** [comment]
> Version 6
> you can't require configstore because the library is now Ecma Script Module(esm)
> use version 5 and you wont get this error
> 
> If you still want to use version 6 make your app module by adding property type : "module" in package json
> 
> CJS and ESM can't get along 🙃

if we can't require then what do we do?

**Comment by Tushar1998** [comment]
You can use node dynamic import

`(async ()=>{
  const configStore = await import("configStore")
   // Now you can use configStore

   console.log(configStore)
})()`
